// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PF_Backend.Data;

#nullable disable

namespace PF_Backend.Migrations
{
    [DbContext(typeof(PF_BackendContext))]
    partial class PF_BackendContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("PF_Backend.Models.Ingredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PortionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PortionsId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("PF_Backend.Models.Portions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdIngredients")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRecipes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdIngredients");

                    b.HasIndex("IdRecipes");

                    b.ToTable("Portions");
                });

            modelBuilder.Entity("PF_Backend.Models.Recipes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PortionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PortionsId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("PF_Backend.Models.Ingredients", b =>
                {
                    b.HasOne("PF_Backend.Models.Portions", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("PortionsId");
                });

            modelBuilder.Entity("PF_Backend.Models.Portions", b =>
                {
                    b.HasOne("PF_Backend.Models.Ingredients", null)
                        .WithMany()
                        .HasForeignKey("IdIngredients")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PF_Backend.Models.Recipes", null)
                        .WithMany()
                        .HasForeignKey("IdRecipes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PF_Backend.Models.Recipes", b =>
                {
                    b.HasOne("PF_Backend.Models.Portions", null)
                        .WithMany("Recipes")
                        .HasForeignKey("PortionsId");
                });

            modelBuilder.Entity("PF_Backend.Models.Portions", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
